name: ChatterBox

on:
  push:
    branches:
    - main
    
jobs:
  black_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Installing testing dependencies
      run: |
        pip install black
    - name: Run black
      run: |
        black -l 100 --check --diff --color .
